### PR TITLE
US-34-fix | Fix the issues with sbs-metrics

### PR DESCRIPTION
**Pull request by yetanotheranand**
# User Story

No US as this PR is to fix the build issues

# Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Change Description

- Fix the code quality issues with sbs-metrics
- Add sbs-project-management as homepage

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by tejg22 — APPROVED** [review]
The commit seems to be fixing the issues.

**Review by vinaythallam — DISMISSED** [review]
This code looks good for fixing the issues , can merge into main

**Review by tejg22 — DISMISSED** [review]
Approving the update.

**Review by vinaythallam — DISMISSED** [review]
Approving the request

**Review by vinaythallam — APPROVED** [review]
Approving the new changes

**Review by tejg22 — APPROVED** [review]

**Pull request merged**
